### ISSUE TITLE
query hang on v$rman_status

### ISSUE THREAD

**Issue by dba0331** [dbworker/dbcollect#1]
hccdump.sh hang on this line:
https://github.com/dbworker/dbcollect/blob/9088a799b9d170cfc8ee5f458292632c5a96da48/script/dump_db_oracle_rman.sh#L38

Recommend add sql hint `/*+ rule */` to the query.

**Comment by dbworker** [comment]
Good feedback! Will fix the issue in next release, publish in one or two week.

**Comment by dbworker** [comment]
solved by add hint
https://github.com/dbworker/dbcollect/blob/4e54fb1096a1fc577c054b25a24881075b195e76/script/dump_db_oracle_rman.sh#L38
