### ISSUE TITLE
Wrong char in xml data

### ISSUE THREAD

**Issue by dba0331** [dbworker/dbcollect#2]
XML data not permit '<' and '&',  this code is not enough:
https://github.com/dbworker/dbcollect/blob/9088a799b9d170cfc8ee5f458292632c5a96da48/script/dump_db_oracle_awr.sh#L79

Should replace '<' and '&' in everywhere before write to xml file.

**Comment by dbworker** [comment]
Good feedback! Will fix the issue in next release, publish in one or two week.

**Comment by dbworker** [comment]
solve by replace special char '&',   '<'
https://github.com/dbworker/dbcollect/blob/4e54fb1096a1fc577c054b25a24881075b195e76/script/dump_db_oracle_inst.sql#L330
and
https://github.com/dbworker/dbcollect/blob/4e54fb1096a1fc577c054b25a24881075b195e76/script/dump_db_oracle_awr.sh#L90
