### ISSUE TITLE
Huge temp sort when query on dba_hist_sysstat

### ISSUE THREAD

**Issue by dba0331** [dbworker/dbcollect#3]
Following sql result in large temp sort:
https://github.com/dbworker/dbcollect/blob/60e185f42c158c1e566a3b560fa0afad4d896b46/script/dump_db_oracle_inst.sql#L415

**Comment by dbworker** [comment]
Yes, sometime it use 1024M temp block.
Sql was modified. please refer to
https://github.com/dbworker/dbcollect/blob/b798eeb30c7a7d35028e19fdaf4b5941be7b4794/script/dump_db_oracle_inst.sql#L456

**Comment by dbworker** [comment]
Yes, sometime it use 1024M temp block.
Some sql in dump_db_oracle_inst.sql was modified,  please refer to
https://github.com/dbworker/dbcollect/blob/b798eeb30c7a7d35028e19fdaf4b5941be7b4794/script/dump_db_oracle_inst.sql#L456
Now query run fast, no large sort.
